PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX ocdp: <http://harth.org/andreas/2017/ocdp/vocabs/ocdp#>

SELECT DISTINCT ?city ?citylabel ?year ?population
WHERE {
  ?x sdmxdim:refArea ?city ;
     <http://citydata.wu.ac.at/ns#hasIndicator> <http://citydata.wu.ac.at/ns#population> ;
     <http://purl.org/linked-data/sdmx/2009/measure#obsValue> ?population ;
     <http://purl.org/dc/terms/date> ?year .

  ?city rdfs:label ?citylabel .
}