PREFIX metroreg: <http://estatwrap.ontologycentral.com/dic/metroreg#>
PREFIX geo: <http://estatwrap.ontologycentral.com/dic/geo#>
PREFIX spatial: <http://geovocab.org/spatial#>

CONSTRUCT {
  ?geo spatial:P ?metroreg .
}
FROM <metroreg1.csv>
WHERE {
  BIND (iri(concat("http://estatwrap.ontologycentral.com/dic/metroreg#", ?MetroID)) AS ?metroreg)
  BIND (iri(concat("http://estatwrap.ontologycentral.com/dic/geo#", ?NUTS3ID)) AS ?geo)
  FILTER (bound(?NUTS3ID) && bound(?MetroID))
}