PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ocdp: <http://harth.org/andreas/2017/ocdp/vocabs/ocdp#>

SELECT DISTINCT ?x ?id ?label ?isocode ?clabel
FROM <http://eurostat.linked-statistics.org/dic/cities>
FROM <http://eurostat.linked-statistics.org/dic/geo>
FROM <eurostat-ls-cities.nt>
WHERE {
  ?x a skos:Concept ; skos:prefLabel ?label ; skos:notation ?id ; ocdp:country ?country .
  ?country skos:prefLabel ?clabel .
  BIND( substr(?id, 0, 2) AS ?isocode)
  FILTER (lang(?label) = "en")
  BIND( substr(?id, 2) AS ?code)
  FILTER (contains(?code, "C"))
}