PREFIX sdmxm: <http://purl.org/linked-data/sdmx/2009/measure#>

SELECT DISTINCT ?x ?val ?g
WHERE {
  GRAPH ?g {
    ?x a qb:Observation ;
       sdmxm:obsValue ?val .
  }
  FILTER (!isNumeric(?val))
}