PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX sdmxm: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX cd: <http://citydata.wu.ac.at/ns#>

SELECT DISTINCT ?city ?indicator ?year ?value
WHERE {
  ?obs sdmxdim:refArea ?city ;
       cd:hasIndicator ?indicator ;
       dcterms:date ?year ;
       sdmxm:obsValue ?value .
}