PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX : <http://harth.org/andreas/2017/citydata/unsd/cities#>
PREFIX unsdmethod: <http://harth.org/andreas/2017/citydata/unsd/unsd-methodology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
CONSTRUCT {
  ?WrapperURI owl:sameAs ?CityURI .
  ?WrapperURINoCode owl:sameAs ?CityURINoCode .
}
FROM <240.csv>
WHERE {
  BIND (URI(CONCAT("http://harth.org/andreas/2017/citydata/unsd/cities#", ?Code_of_City, substr(?City_type, 0, 2))) AS ?CityURI)
  BIND (URI(CONCAT("http://citydata.wu.ac.at/resource/", ?Country_or_Area_Code, "/", ?Code_of_City, "#", substr(?City_type, 0, 2))) AS ?WrapperURI)

  BIND (URI(CONCAT("http://harth.org/andreas/2017/citydata/unsd/cities#", ?Code_of_City)) AS ?CityURINoCode)
  BIND (URI(CONCAT("http://citydata.wu.ac.at/resource/", ?Country_or_Area_Code, "/", ?Code_of_City)) AS ?WrapperURINoCode)
}